//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsSystemAppProto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Images = new HashSet<Images>();
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
            this.Emails = new HashSet<Emails>();
            this.Addresses = new HashSet<Addresses>();
            this.IMs = new HashSet<IMs>();
            this.SocialNetworks = new HashSet<SocialNetworks>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<Images> Images { get; set; }
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
        public virtual ICollection<Emails> Emails { get; set; }
        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<IMs> IMs { get; set; }
        public virtual ICollection<SocialNetworks> SocialNetworks { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
