//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsSystemAppProto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactsModelContainer : DbContext
    {
        public ContactsModelContainer()
            : base("name=ContactsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> ContactSet { get; set; }
        public DbSet<Images> ImagesSet { get; set; }
        public DbSet<PhoneNumbers> PhoneNumbersSet { get; set; }
        public DbSet<Emails> EmailsSet { get; set; }
        public DbSet<Addresses> AddressesSet { get; set; }
        public DbSet<IMs> IMsSet { get; set; }
        public DbSet<SocialNetworks> SocialNetworksSet { get; set; }
        public DbSet<Comments> CommentsSet { get; set; }
    }
}
